const allTopics = [
    'React',
    'HTML',
    'JavaScript',
    'C#',
    'Programming',
    'Anime',
    'Manga',
    'Yu-Gi-Oh!',
    'Pokémon',
    'Video Games',
    'PC',
    'PS4',
    'Xbox',
    'Web Development',
    'Mobile Development',
    'AI and Machine Learning',
    'Data Science',
    'Cybersecurity',
    'Cloud Computing',
    'DevOps',
    'Blockchain',
    'Game Development',
    'Software Engineering',
    'Open Source',
    'Computer Science',
    'Networking',
    'Database Management',
    'UI/UX Design',
    'Agile Methodologies',
    'Scrum',
    'Project Management',
    'Digital Marketing',
    'SEO',
    'Fortnite',
    'Call of Duty',
    'League of Legends',
    'Dota 2',
    'Counter-Strike',
    'Valorant',
    'Overwatch',
    'Minecraft',
];

export default allTopics;

//CLOUDINARY_URL=cloudinary://537959291836361:EShckaASsnDaZboXOgMm0ErZ4hY@do3afaqmr